name: t_learn
description: E-Learning Platform.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  firebase_analytics: ^9.1.10
  firebase_crashlytics: ^2.8.2
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.2.1
  firebase_storage: ^10.3.1
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  google_sign_in: ^5.3.3
  easy_localization: ^3.0.1
  page_transition: ^2.0.5
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  url_launcher: ^6.1.4
  app_settings: ^4.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_extra_bold.ttf
          weight: 900
        - asset: assets/fonts/poppins_bold.ttf
          weight: 800
        - asset: assets/fonts/poppins_semi_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins_regular.ttf
          weight: 300
        - asset: assets/fonts/poppins_light.ttf
          weight: 100

